vich_uploader:
    db_driver: orm

    mappings:
        client_images:
            uri_prefix: '%app.path.client_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.client_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true